name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup PHP and Composer
      - name: Install Apache and PHP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update 
            sudo apt upgrade -y

            # Install PHP and Apache
            sudo apt install -y apache2 php8.3 libapache2-mod-php8.3 php8.3-cli php8.3-common php8.3-curl php8.3-mbstring php8.3-xml php8.3-zip php8.3-mysql unzip curl git

            # Install Composer
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

            # Enable Apache mod_rewrite
            sudo systemctl start apache2
            sudo systemctl enable apache2
            sudo a2enmod rewrite

            # Set up Apache virtual host
            sudo bash -c 'cat <<EOF > /etc/apache2/sites-available/laravel.conf
            <VirtualHost *:80>
                ServerAdmin webmaster@localhost
                DocumentRoot /var/www/laravel/public

                <Directory /var/www/laravel/public>
                    Options Indexes FollowSymLinks
                    AllowOverride All
                    Require all granted
                </Directory>

                ErrorLog \${APACHE_LOG_DIR}/error.log
                CustomLog \${APACHE_LOG_DIR}/access.log combined
            </VirtualHost>
            EOF'

            # Enable the virtual host
            sudo a2dissite 000-default.conf
            sudo a2ensite laravel.conf

            # Configure Permissions
            sudo mkdir -p /var/www/laravel
            sudo chown -R ubuntu:www-data /var/www/laravel
            sudo chmod -R 775 /var/www/laravel

            # Restart Apache
            sudo systemctl restart apache2

      # Step 3: Deploy to EC2 server
      - name: Deploy to Server EC2 AWS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      # Step 4: Execute remote SSH commands
      - name: Install dependencies and configure Laravel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the Laravel project directory
            cd /var/www/laravel
            
            # Copy .env.example to .env
            sudo cp .env.example .env
            
            # Update .env with environment variables
            sudo bash -c 'echo "APP_URL=https://${{ secrets.EC2_DNS }}" >> .env'
            sudo bash -c 'echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env'
            sudo bash -c 'echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env'
            sudo bash -c 'echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env'
            sudo bash -c 'echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env'
            
            # Install dependencies
            sudo composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # Generate application key and optimize caches
            sudo php artisan key:generate
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            php artisan optimize
            
            # Restart Apache to apply changes
            sudo systemctl restart apache2